version: "3.8"

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: php_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scriptdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    command: --character-set-server=utf8_turkish_ci --collation-server=utf8_turkish_ci
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
